name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for GH Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check for changes in 'blog'
        id: check_changes
        run: |
          # Get the list of files changed in the last commit
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"

          # Check if any of the changed files are in the specified directory
          if echo "$CHANGED_FILES" | grep -q '^blog/'; then
            echo "Changes detected in 'blog'"
            echo "::set-output name=changes::true"
          else
            echo "No changes detected in 'blog'"
            echo "::set-output name=changes::false"
          fi

      - name: Remove old build files
        run: |
          rm -rf docs/.vitepress/dist

      - name: Install dependencies and build
        run: |
          npm ci
          if [ "${{ steps.check_changes.outputs.changes }}" = "true" ]; then
            npm run generate-index
            git update-index --again
          fi
          npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
